**Data pre processing with health dataset.**

In [36]:
import numpy as np
import pandas as pd

In [37]:
df = pd.read_csv('../sample_data/health_data.csv.txt')
df.head()

   Duration        Date  Pulse  Maxpulse  Calories
0        60  2020/12/01    110       130     409.1
1        60  2020/12/02    117       145     479.0
2        60  2020/12/03    103       135     340.0
3        45  2020/12/04    109       175     282.4
4        45  2020/12/05    117       148     406.0

In [38]:
df.shape

(32, 5)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [40]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [41]:
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60    20201225    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [42]:
x = df['Calories'].mean()
df.fillna({'Calories':x},inplace = True)
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130    409.10
1         60  2020/12/02    117       145    479.00
2         60  2020/12/03    103       135    340.00
3         45  2020/12/04    109       175    282.40
4         45  2020/12/05    117       148    406.00
5         60  2020/12/06    102       127    300.00
6         60  2020/12/07    110       136    374.00
7        450  2020/12/08    104       134    253.30
8         30  2020/12/09    109       133    195.10
9         60  2020/12/10     98       124    269.00
10        60  2020/12/11    103       147    329.30
11        60  2020/12/12    100       120    250.70
12        60  2020/12/12    100       120    250.70
13        60  2020/12/13    106       128    345.30
14        60  2020/12/14    104       132    379.30
15        60  2020/12/15     98       123    275.00
16        60  2020/12/16     98       120    215.20
17        60  2020/12/17    100       120    300.00
18        45  2020/12/18     90       112    304.68
19        60  2020/12/19    103       123    323.00
20        45  2020/12/20     97       125    243.00
21        60  2020/12/21    108       131    364.20
22        45         NaN    100       119    282.00
23        60  2020/12/23    130       101    300.00
24        45  2020/12/24    105       132    246.00
25        60    20201225    102       126    334.50
26        60  2020/12/26    100       120    250.00
27        60  2020/12/27     92       118    241.00
28        60  2020/12/28    103       132    304.68
29        60  2020/12/29    100       132    280.00
30        60  2020/12/30    102       129    380.30
31        60  2020/12/31     92       115    243.00

In [48]:
x = df['Calories'].mode()[0]
df.fillna({'Calories':x},inplace = True)
print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7         45 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
12        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
22        45        NaT    100       119    282.00
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00

In [51]:
df['Date'] = pd.to_datetime(df['Date'],format = 'mixed')
print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7         45 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
12        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
22        45        NaT    100       119    282.00
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00

In [52]:
df.loc[7,'Duration'] = 45
print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7         45 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
12        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
22        45        NaT    100       119    282.00
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00

In [54]:
df.dropna(inplace = True)
print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7         45 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
12        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00

In [55]:
df.shape

(31, 5)

In [56]:
df.drop_duplicates(inplace = True)
print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7         45 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00

In [57]:
df.shape

(30, 5)

In [58]:
for x in df.index:
    if df.loc[x,'Duration'] > 120:
        df.loc[x,'Duration'] = 120
print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7         45 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00

In [59]:
df.shape

(30, 5)

In [61]:
for x in df.index:
    if df.loc[x,'Duration'] > 60:
        df.drop(x,inplace = True )
print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7         45 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00

In [62]:
df.shape

(30, 5)